# General configuration
spring.application.name=ptracker_backend
server.port=${PTRACKER_BACKEND_PORT:8080}

# MySQL Database configuration (Docker Compose defaults)
spring.datasource.url=jdbc:mysql://${PTRACKER_BACKEND_DB_HOST:localhost}:${PTRACKER_BACKEND_DB_PORT:3306}/${PTRACKER_BACKEND_DB_NAME:ptracker}?useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=UTC
spring.datasource.username=${PTRACKER_BACKEND_DB_USERNAME:root}
spring.datasource.password=${PTRACKER_BACKEND_DB_PASSWORD:admin}
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

# JPA/Hibernate configuration
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQLDialect
spring.jpa.properties.hibernate.format_sql=true

# Security & authentication configuration
spring.security.user.name=${PTRACKER_BACKEND_SECURITY_USER_NAME:admin}
spring.security.user.password=${PTRACKER_BACKEND_SECURITY_USER_PASSWORD:admin}

# OpenAPI configuration
springdoc.api-docs.enabled=true
springdoc.swagger-ui.enabled=true

# Authentication configuration
app.admin.email=${PTRACKER_BACKEND_ADMIN_USERNAME:admin@example.com}
app.admin.password=${PTRACKER_BACKEND_ADMIN_PASSWORD:admin}
app.jwt-secret=${PTRACKER_BACKEND_JWT_SECRET:y6cmo3yrch0uil79t0fwhj0mt3b8534k}
app.jwt-auth-expiration-ms=${PTRACKER_BACKEND_JWT_EXPIRATION_MS:86400000}
app.jwt-refresh-expiration-ms=${PTRACKER_BACKEND_JWT_REFRESH_EXPIRATION_MS:86400000}

# Logs configuration
logging.level.root=INFO
logging.level.com.project=DEBUG
logging.file.name=logs/app.log
logging.pattern.console=%d{yyyy-MM-dd HH:mm:ss} [%thread] %-5level %logger{36} - %msg%n
logging.pattern.file=%d{yyyy-MM-dd HH:mm:ss} [%thread] %-5level %logger{36} - %msg%n
