# ======================================================================
# This is a docker-compose file that allows to run 
# application dependencies (e.g. database) for development purposes.
# 
# To run: (while being in the repo root directory)
# > docker-compose -f CONTRIB/docker/app-dependencies.yaml up -d
# 
# To stop:
# > docker-compose -f CONTRIB/docker/app-dependencies.yaml down
# 
# After running the file, you should be able to access:
# - mongo-express at http://localhost:8081
# - mongodb at mongodb://localhost:27017
# ======================================================================

version: '3.8'

services:
  mongo:
    image: mongo:latest
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: admin
      ME_CONFIG_MONGODB_ADMINPASSWORD: admin
      MONGO_INITDB_DATABASE: ptracker
    volumes:
      - mongo-dev-data:/data/db
    ports:
      - "5005:27017"

  mongoexpress:
    image: mongo-express:latest
    environment:
      ME_CONFIG_MONGODB_SERVER: mongo
      ME_CONFIG_MONGODB_ADMINUSERNAME: admin
      ME_CONFIG_MONGODB_ADMINPASSWORD: admin
      ME_CONFIG_BASICAUTH: "false"
    ports:
      - "8085:8081"
    depends_on:
      - mongo

volumes:
  mongo-dev-data:
    driver: local
