# ======================================================================
# This is a docker-compose file that allows to run 
# application dependencies (e.g. database) for development purposes.
# 
# To run: (while being in the repo root directory)
# > docker-compose -f CONTRIB/docker/app-dependencies.yaml up -d
# 
# To stop:
# > docker-compose -f CONTRIB/docker/app-dependencies.yaml down
# 
# After running the file, you should be able to access:
# - mongo-express at http://localhost:8081
# - mongodb at mongodb://localhost:27017
# ======================================================================

version: '3.8'

services:
  ptracker-dev-mongodb:
    image: mongo:latest
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: admin
      MONGO_INITDB_DATABASE: ptracker
    volumes:
      - mongo-dev-data:/data/db
    ports:
      - "27017:27017"

  ptracker-dev-mongo-express:
    image: mongo-express:latest
    environment:
      ME_CONFIG_MONGODB_SERVER: ptracker-mongodb
      ME_CONFIG_MONGODB_ADMINUSERNAME: admin
      ME_CONFIG_MONGODB_ADMINPASSWORD: admin
      ME_CONFIG_BASICAUTH_USERNAME: admin
      ME_CONFIG_BASICAUTH_PASSWORD: admin
    ports:
      - "8081:8085"
    depends_on:
      - ptracker-dev-mongodb

volumes:
  mongo-dev-data:
    driver: local
