# ======================================================================
# Docker Compose file to run the whole application with MySQL for production.
#
# To run:
# docker-compose -f CONTRIB/docker/app-release.yaml up -d
#
# To stop:
# docker-compose -f CONTRIB/docker/app-release.yaml down
#
# After running, you should be able to access:
# - frontend app at http://localhost:8090
# - backend app at http://localhost:8095
# ======================================================================

version: '3.8'

services:
  ptracker-release-mysql:
    image: mysql:8.0
    environment:
      MYSQL_ROOT_PASSWORD: admin
      MYSQL_DATABASE: ptracker
      MYSQL_USER: user
      MYSQL_PASSWORD: password
    volumes:
      - mysql-release-data:/var/lib/mysql
    ports:
      - "3306:3306"

  ptracker-release-frontend:
    build:
      context: ../../FRONTEND
      dockerfile: ../CONTRIB/docker/frontend.Dockerfile
    ports:
      - "8090:80"
    environment:
      - NODE_ENV=production
  
  ptracker-release-backend:
    build:
      context: ../../BACKEND
      dockerfile: ../CONTRIB/docker/backend.Dockerfile
    ports:
      - "8095:8095"
    environment:
      - PTRACKER_BACKEND_PORT=8095
      - PTRACKER_BACKEND_DB_HOST=ptracker-release-mysql
      - PTRACKER_BACKEND_DB_PORT=3306
      - PTRACKER_BACKEND_DB_USER=user
      - PTRACKER_BACKEND_DB_PASSWORD=password
      - PTRACKER_BACKEND_DB_NAME=ptracker

volumes:
  mysql-release-data:
    driver: local
