name: ci

on:
  push:

jobs:
  build_backend:
    name: Build backend
    runs-on: "ubuntu-latest"
    steps:
      - uses: actions/checkout@v4

      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
            java-version: '21'
            distribution: 'temurin'
            cache: gradle
      
      - name: Build with Gradle
        run: chmod a+x ./gradlew && ./gradlew clean test jacocoTestReport
        working-directory: ./BACKEND
      
      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v4
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          files: BACKEND/build/reports/jacoco/test/jacocoTestReport.xml
          flags: unittests
          name: codecov-coverage
      
  build_frontend:
    name: Build frontend
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Cache node modules
        uses: actions/cache@v4
        with:
          path: ~/.npm
          key: ${{ runner.os }}-node-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-node-
            
      - name: Setup node.js environment
        uses: actions/setup-node@v4
        with:
          node-version: "20.x"

      - name: Install dependencies
        run: npm ci
        working-directory: ./FRONTEND

      - name: Build application
        run: npm run build
        working-directory: ./FRONTEND
        
