name: Update Languages

on:
  push:
    branches: [main]
  schedule:
    - cron: '0 0 * * 1'  # co poniedziałek
  workflow_dispatch:

jobs:
  update-languages:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'

      - name: Install dependencies
        run: pip install requests

      - name: Run language update script
        run: python update_languages.py

      - name: Commit and push changes
        run: |
          git config --global user.name 'github-actions'
          git config --global user.email 'github-actions@github.com'
          git add README.md
          git commit -m '📊 Auto-update languages used' || echo "No changes to commit"
          git push
